services:
  backend:
    build:
      context: ./backEnd
      dockerfile: Dockerfile
    container_name: review-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    user: "0:0"
    volumes:
      - ./backEnd/src:/app/src
      - ./backEnd/app.py:/app/app.py
      - ./backEnd/attachments:/app/attachments
      - ./backEnd/vectorstores:/app/vectorstores
      - ./backEnd/db:/app/db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontEnd
      dockerfile: Dockerfile
    container_name: review-frontEnd
    ports:
      - "8080:80"
    volumes:
      - ./frontEnd/public:/usr/share/nginx/html
      - ./frontEnd/src:/usr/share/nginx/html/src
    depends_on:
      - backend
    restart: unless-stopped
